In [1]:
import numpy as np
import matplotlib.pyplot as plt  # To visualize
import pandas as pd  # To read data
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
from sklearn.pipeline import Pipeline
import missingno as msno

In [2]:
df = pd.read_csv('merged_times.csv', engine='python')  # load data set

In [26]:
round(df.groupby('parte_relac')[['tempo_entre_homologacao_empenho', 
                           'tempo_entre_empenho_liquidacao',
                           'tempo_entre_liquidacao_pagamento',
                           'tempo_entre_empenho_pagamento',
                           'tempo_entre_homologacao_pagamento']].agg([np.mean, np.median, np.std, min, max]).T,1)

parte_relac                                    0       1
tempo_entre_homologacao_empenho   mean      56.1   101.8
                                  median     0.0     0.0
                                  std      188.8   257.4
                                  min     -231.0     0.0
                                  max     3652.0  1673.0
tempo_entre_empenho_liquidacao    mean      83.3    95.1
                                  median    56.0    71.0
                                  std       90.6    93.8
                                  min     -233.0  -260.0
                                  max     2177.0  1620.0
tempo_entre_liquidacao_pagamento  mean      11.6    11.4
                                  median     3.0     2.0
                                  std       24.6    24.2
                                  min        0.0     0.0
                                  max      344.0   249.0
tempo_entre_empenho_pagamento     mean      94.9   106.5
                                  median    69.0    87.0
                                  std       92.3    93.8
                                  min     -233.0  -260.0
                                  max     2177.0  1620.0
tempo_entre_homologacao_pagamento mean     153.4   209.6
                                  median   100.0   117.5
                                  std      205.3   278.3
                                  min     -139.0  -260.0
                                  max     3741.0  1821.0

In [229]:
for i in df.columns:
    if ('valor_') in i:
        try:
            df[i] = df[i].apply(lambda x: (float(x.strip().replace("R$ ","").replace(".","").replace(",",".").replace("-",""))))
            df[i] = df[i].fillna(0)
        except:
            continue