In [106]:
import sqlite3
from sqlite3 import Error
import numpy as np
import pandas as pd
import json
import os
import glob
import unicodedata as ud

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:

def beautifier_cols(dataframe):
    cols = dataframe.columns
    cols_new = [j.lower().strip().replace(" ", "_") for j in cols]
    df_new = dataframe.rename(columns=dict(zip(cols, cols_new))).drop_duplicates().reset_index(drop=True)
    return df_new


def credores():
    # 2016
    path = r'./raw_data/cred_2016/'
    files = glob.glob(path + "credores_2016_*.csv")
    credores_list = []
    for filename in files:
        df = pd.read_csv(filename, index_col=None, header=0)
        df = df.rename(columns={'Valor Em LiquidaÃ§Ã£o': 'Valor Em Liquidação'})
        credores_list.append(df)
    cred16 = pd.concat(credores_list, axis=0, ignore_index=True, sort=True).reset_index(drop=True)
    cred16 = cred16.drop(cred16.filter(like=r'Unnamed').columns, axis=1)
    cred16 = cred16.iloc[cred16['Nome'].str.normalize('NFKD').argsort()]  # sort columns containing special chars

    # 2018
    path = r'./raw_data/cred_2018/'
    files = glob.glob(path + "credores_2018_*.csv")
    credores_list = []
    for filename in files:
        df = pd.read_csv(filename, index_col=None, header=0)
        df = df.rename(columns={'Valor Em LiquidaÃ§Ã£o': 'Valor Em Liquidação'})
        credores_list.append(df)
    cred18 = pd.concat(credores_list, axis=0, ignore_index=True, sort=True).reset_index(drop=True)
    cred18 = cred18.drop(cred18.filter(like=r'Unnamed').columns, axis=1)
    cred18 = cred18.iloc[cred18['Nome'].str.normalize('NFKD').argsort()]  # sort columns containing special chars
    creds = pd.concat([pd.read_csv('raw_data/credores_2015.csv', sep="\t"),
                       cred16,
                       pd.read_csv('./raw_data/credores_2017.csv'),
                       cred18,
                       pd.read_csv('./raw_data/credores_2019.csv', sep="\t")], sort=True).drop_duplicates()
    creds = creds[['Nome', 'CNPJ/CPF', 'Valor Empenhado', 'Valor Em Liquidação',
                   'Valor Liquidado', 'Valor Pago', 'Valor Anulado', 'ano']]
    creds = beautifier_cols(creds)
    creds = creds.iloc[creds['nome'].str.normalize('NFKD').argsort()]  # sort columns containing special chars
    creds = creds.sort_values(['ano', 'nome']).sort_index()
    return creds


def credores_liquida():
    cred_liq = ['credores_liquidacoes_2015.csv',
                'credores_liquidacoes_2016.csv',
                'credores_liquidacoes_2017.csv',
                'credores_liquidacoes_2018.csv',
                'credores_liquidacoes_2019.csv']
    credores_liquid = pd.DataFrame()
    for i in cred_liq:
        file = './raw_data/' + str(i)
        df = pd.read_csv(file, sep='\t')
        df['ano'] = i.split('.')[0][-4:]
        credores_liquid = credores_liquid.append(df).drop_duplicates()

    credores_liquid = credores_liquid[~credores_liquid['Data da Liquidação'].str.contains("Data da")]
    credores_liquid = credores_liquid[['Data da Liquidação', 'Número de Liquidação', 'Complemento Histórico',
                                       'Valor Liquidado', 'Valor Estornado', 'credor', 'empenho', 'ano']]
    credores_liquid['empenho'] = credores_liquid['empenho'].astype(int)
    credores_liquid = beautifier_cols(credores_liquid)
    return credores_liquid


def credores_pagtos():
    cred_pagtos = ['credores_pagamentos_2015.csv',
                   'credores_pagamentos_2016.csv',
                   'credores_pagamentos_2017.csv',
                   'credores_pagamentos_2018.csv',
                   'credores_pagamentos_2019.csv']
    credores_pagamentos = pd.DataFrame()
    for i in cred_pagtos:
        file = './raw_data/' + str(i)
        df = pd.read_csv(file, sep='\t')
        df['ano'] = i.split('.')[0][-4:]
        credores_pagamentos = credores_pagamentos.append(df).drop_duplicates()

    credores_pagamentos = credores_pagamentos[~credores_pagamentos['Data do Pagamento'].str.contains("Data do Pagamento")]
    credores_pagamentos = credores_pagamentos[['Data do Pagamento', 'Número do Pagamento', 'Número de liquidação',
                                               'Complemento Histórico', 'Valor Pago', 'Valor Estornado', 'credor',
                                               'empenho', 'ano']]
    credores_pagamentos = beautifier_cols(credores_pagamentos)
    return credores_pagamentos


# DETALHES EMPENHOS
def detalhes_empenhos(df_credores):
    det_emp = ['detalhes_emp_2015.csv',
               'detalhes_emp_2016.csv',
               'detalhes_emp_2017.csv',
               'detalhes_emp_2018.csv',
               'detalhes_emp_2019.csv']
    detalhes_emp_list = []
    for i in det_emp:
        file = './raw_data/' + str(i)
        df = pd.read_csv(file)
        df['ano_referencia'] = i.split('.')[0][-4:]
        df = df.iloc[df['Credor'].str.normalize('NFKD').argsort()]  # sort columns containing special chars
        detalhes_emp_list.append(df)
    detalhes_emp = pd.concat(detalhes_emp_list, sort=True).drop_duplicates()

    detalhes_emp = detalhes_emp.sort_index(axis=1)
    detalhes_emp = detalhes_emp.loc[:, 'Ação de Governo':]
    detalhes_emp = detalhes_emp.loc[:, ~detalhes_emp.columns.duplicated()]

    detalhes_emp = beautifier_cols(detalhes_emp)
    detalhes_emp = detalhes_emp.merge(df_credores[['nome', 'cnpj/cpf']],
                                      left_on='credor',
                                      right_on='nome',
                                      how='inner')
    detalhes_emp = detalhes_emp[['data_emissão_empenho', 'número_do_empenho', 'unidade_gestora',
                                 'credor', 'cnpj/cpf', 'valor_empenhado', 'valor_em_liquidação', 'valor_liquidado',
                                 'valor_pago', 'valor_anulado', 'atualizado_em', 'período',
                                 'tipo_empenho', 'categoria',
                                 'órgão', 'unidade', 'função', 'subfunção', 'programa_de_governo',
                                 'ação_de_governo', 'esfera', 'ie',
                                 'categoria_econômica', 'grupo_da_despesa', 'modalidade_de_aplicação',
                                 'natureza_da_despesa', 'desdobramento_da_despesa', 'fonte_de_recursos',
                                 'detalhamento_da_fonte', 'licitação', 'número_da_licitação',
                                 'data_de_homologação', 'processo_da_compra', 'processo_administrativo', 'contrato',
                                 'convênio', 'empenhado', 'em_liquidação', 'liquidado',
                                 'pago', 'anulado', 'ano_referencia']]

    detalhes_emp = detalhes_emp.reset_index(drop=True)
    detalhes_emp['número_do_empenho'] = detalhes_emp['número_do_empenho'].astype(int)
    detalhes_emp['credor'] = detalhes_emp['credor'].apply(lambda x: ud.normalize('NFKD', x))
    detalhes_emp = detalhes_emp.sort_values(['ano_referencia', 'credor']).drop_duplicates().reset_index(drop=True)

    d_emi = pd.to_datetime(detalhes_emp['data_emissão_empenho'])
    d_hom = pd.to_datetime(detalhes_emp['data_de_homologação'])

    detalhes_emp['tempo_entre_homologacao_empenho'] = (d_emi - d_hom) / np.timedelta64(1, 'D')

    return detalhes_emp

In [3]:
df_credores = credores()
credores_liquidacoes = credores_liquida()
credores_pagamentos = credores_pagtos()
detalhes_emp = detalhes_empenhos(df_credores)

In [79]:
detalhes_emp = detalhes_emp.rename(columns={'número_do_empenho':'empenho', 'ano_referencia':'ano'})
credores_pagamentos['empenho'] = credores_pagamentos.empenho.astype(int)

# dfs = [detalhes_emp, credores_pagamentos, credores_liquidacoes]

In [83]:
from functools import reduce

dfs = [credores_pagamentos, credores_liquidacoes]
dff = reduce(lambda x,y: pd.merge(x,y,on=['empenho','credor','número_de_liquidação','ano']), dfs)
d = pd.merge(detalhes_emp, dff, on=['empenho', 'credor', 'ano'])

In [ ]:
d[(d.credor=='KROMAC COMERCIO E SERVICOS LTDA ME')&(d.empenho==834)]

In [74]:
detalhes_emp = detalhes_emp.rename(columns={'número_do_empenho':'empenho'})
credores_pagamentos['empenho'] = credores_pagamentos.empenho.astype(int)

df = pd.merge(credores_liquidacoes, detalhes_emp, on = ['empenho', 'credor'])
df_final = pd.merge(credores_pagamentos, df, on = ['credor', 'empenho', 'número_de_liquidação'])

df_dates = df_final[['data_da_liquidação', 'data_emissão_empenho','data_de_homologação', 'data_do_pagamento']]

for i in df_dates:
    df_dates = df_dates.copy()
    df_dates[i] = pd.to_datetime(df_dates[i], format='%d/%m/%Y')

tempo_entre_homologacao_empenho = (df_dates['data_emissão_empenho'] - df_dates['data_de_homologação']) / np.timedelta64(1, 'D')

tempo_entre_empenho_liquidacao = (df_dates['data_da_liquidação'] - df_dates['data_emissão_empenho']) / np.timedelta64(1, 'D')

tempo_entre_liquidacao_pagamento = (df_dates['data_do_pagamento'] - df_dates['data_da_liquidação']) / np.timedelta64(1, 'D')

tempo_entre_empenho_pagamento = (df_dates['data_do_pagamento'] - df_dates['data_emissão_empenho']) / np.timedelta64(1, 'D')

tempo_total = (df_dates['data_do_pagamento'] - df_dates['data_de_homologação']) / np.timedelta64(1, 'D')

df_final['tempo_entre_empenho_liquidacao'] = tempo_entre_empenho_liquidacao
df_final['tempo_entre_liquidacao_pagamento'] = tempo_entre_liquidacao_pagamento
df_final['tempo_total2'] = tempo_entre_empenho_pagamento
df_final['tempo_total'] = tempo_total

df_final['tempo_entre_homologacao_empenho'] = tempo_entre_homologacao_empenho

In [ ]:
df_final[['credor', 'data_da_liquidação', 'data_emissão_empenho','data_de_homologação', 'data_do_pagamento',
         'tempo_entre_homologacao_empenho','tempo_entre_empenho_liquidacao', 'tempo_entre_liquidacao_pagamento',
          'tempo_total2', 'tempo_total']][df_final.credor=='ALFREDO TANOS FILHO'].sort_values('data_de_homologação')

In [155]:
dfexp = pd.read_csv('exp.csv')

In [158]:
dfexp[(dfexp.Credor.isin(cr))&(dfexp['Número Empenho']==5)]

,Unnamed: 0,Credor,Data Emissão Empenho,Número Empenho,Unidade Gestora_x,Valor Anulado,Valor Em Liquidação,Valor Empenhado,Valor Liquidado,Valor Pago,detalhe_empenho,0 Ano,0034 Ano,0052 Ano,0176 Ano,0180 Ano,0182 Ano,072 Ano,1164 Ano,14165 Ano,14166 Ano,1701996 Ano,170996 Ano,171145 Ano,171447 Ano,171586 Ano,171810 Ano,172265 Ano,18051 Ano,200 Ano,22771 Ano,23010 Ano,23018 Ano,24969 Ano,26409 Ano,280010 Ano,280016 Ano,280017 Ano,280022 Ano,280023 Ano,280031 Ano,280036 Ano,280038 Ano,280040 Ano,280051 Ano,280072 Ano,280078 Ano,280125 Ano,28531 Ano,28532 Ano,28533 Ano,2981 Ano,30425 Ano,30426 Ano,34 Ano,421 Ano,426 Ano,510001 Ano,510002 Ano,510015 Ano,510021 Ano,510023 Ano,510045 Ano,510057 Ano,510088 Ano,510101 Ano,510135 Ano,62688 Ano,63034 Ano,64105 Ano,689 Ano,759 Ano,778 Ano,900221 Ano,931 Ano,AG.240042 Ano,AG.240043 Ano,AG.240130 Ano,Ação de Governo,Ano,Anulado,Atualizado em,Categoria,Categoria Econômica,Contrato,Convênio,Data de Homologação,Desdobramento da Despesa,Detalhamento da Fonte,Em Liquidação,Empenhado,Esfera,Fonte de Recursos,Função,Grupo da Despesa,IE,Licitação,Liquidado,Modalidade de Aplicação,Natureza da Despesa,No Contrato,Nota Explicativa,Nr. Licitação,Número da Licitação,Órgão,Pago,Período,Processo Administrativo,Processo da Compra,Programa de Governo,SubFunção,Tipo Empenho,Unidade,Unidade Gestora_y
1322,4547,SINGULAR GESTAO DE SERVICOS LTDA,11/01/2016,5.0,PREFEITURA DE MACAÉ - 0000,"R$ 0,00","R$ 0,00","R$ 2.366.079,38","R$ 2.366.079,38","R$ 2.366.079,38","<table cellpadding=""1px"" cellspacing=""0px"" cla...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,294 - Alimentação Escolar,2015,"R$ 0,00",28/12/2019 00:31,Comum,3 - DESPESAS CORRENTES,NaN,NaN,NaN,3.3.90.39.41 - FORNECIMENTO DE ALIMENTACAO,0 -,"R$ 0,00","R$ 2.366.079,38",Fiscal,RECURSOS ORDINÁRIOS - TESOURO,12 - Educação,3.3 - OUTRAS DESPESAS CORRENTES,NaN,Pregão Presencial,"R$ 2.366.079,38",3.3.90 - Aplicações Diretas,3.3.90.39 - OUTROS SERVIÇOS DE TERCEIROS - PE...,NaN,NaN,NaN,003/15,SECRETARIA MUNICIPAL DE EDUCAÇÃO,"R$ 2.366.079,38",Janeiro a Dezembro,/0,Processo da Compra:,112 - UNIVERSALIZAÇÃO DO ATENDIMENTO AO ESCO...,361 - Ensino Fundamental,Orçamentário,Secretaria Municipal de Educação,PREFEITURA DE MACAÉ - 0000

In [94]:
dfc = pd.read_csv('credores_empenhos_2016.csv')

In [97]:
dfc.head()

,Credor,Data Emissão Empenho,Número do Empenho,Unidade Gestora,Valor Anulado,Valor Em Liquidação,Valor Empenhado,Valor Liquidado,Valor Pago,detalhe_empenho
0,JUSSARA CUNHA NATALINO,12/04/2016,344.0,FUNDO MUNICIPAL DE SAÚDE - 0003,"R$ 4.000,00","R$ 0,00","R$ 4.000,00","R$ 0,00","R$ 0,00","<table cellpadding=""1px"" cellspacing=""0px"" cla..."
1,JUVENAL MONTEIRO GREGORIO,06/04/2016,7.0,FUNDO MUN.HABIT.E INTERES. SOCIAL - 0028,"R$ 0,00","R$ 0,00","R$ 600,00","R$ 600,00","R$ 600,00","<table cellpadding=""1px"" cellspacing=""0px"" cla..."
2,JUVENIL ALVES DE MOURA JUNIOR,11/08/2016,244.0,FUNDO MUNIC. TRANSPORTE E TRANSITO - 026,"R$ 0,00","R$ 0,00","R$ 223,74","R$ 223,74","R$ 223,74","<table cellpadding=""1px"" cellspacing=""0px"" cla..."
3,K.J.B. PRODUTORA DE EVENTOS LTDA - EPP,16/08/2016,1369.0,PREFEITURA DE MACAÉ - 0000,"R$ 0,00","R$ 0,00","R$ 500.000,00","R$ 500.000,00","R$ 500.000,00","<table cellpadding=""1px"" cellspacing=""0px"" cla..."
4,K.J.B. PRODUTORA DE EVENTOS LTDA - EPP,02/05/2016,964.0,PREFEITURA DE MACAÉ - 0000,"R$ 0,00","R$ 0,00","R$ 500.000,00","R$ 500.000,00","R$ 500.000,00","<table cellpadding=""1px"" cellspacing=""0px"" cla..."

In [100]:
dfc[(dfc.Credor.isin(cr))&(dfc['Número do Empenho']==5)].loc[3167:,:].detalhe_empenho.to_csv('test1')
dfc[(dfc.Credor.isin(cr))&(dfc['Número do Empenho']==5)].loc[:2794,:].detalhe_empenho.to_csv('test2.html')

/Users/renatoaranha/PycharmProjects/portaltransparenciamacae/venv_portal/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.
/Users/renatoaranha/PycharmProjects/portaltransparenciamacae/venv_portal/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.

In [174]:
# df = pd.read_csv('./raw_data/detalhes_emp_2016.csv')
df = pd.read_csv('detalhes_emp_2016.csv')

In [175]:
cr = ['SINGULAR GESTAO DE SERVICOS LTDA', 'AMARO LUIZ ALVES DA SILVA E OUTROS', 'ERGA COMERCIO DE AREIA LTDA -ME']

df[(df.Credor.isin(cr))&(df['Número Empenho']==5)].drop_duplicates()

,Credor,Data Emissão Empenho,Número Empenho,Unidade Gestora_x,Valor Anulado,Valor Em Liquidação,Valor Empenhado,Valor Liquidado,Valor Pago,detalhe_empenho,0 Ano,0034 Ano,0052 Ano,0176 Ano,0180 Ano,0182 Ano,072 Ano,1164 Ano,14165 Ano,14166 Ano,1701996 Ano,170996 Ano,171145 Ano,171447 Ano,171586 Ano,171810 Ano,172265 Ano,18051 Ano,200 Ano,22771 Ano,23010 Ano,23018 Ano,24969 Ano,26409 Ano,280010 Ano,280016 Ano,280017 Ano,280022 Ano,280023 Ano,280031 Ano,280036 Ano,280038 Ano,280040 Ano,280051 Ano,280072 Ano,280078 Ano,280125 Ano,28531 Ano,28532 Ano,28533 Ano,2981 Ano,30425 Ano,30426 Ano,34 Ano,421 Ano,426 Ano,510001 Ano,510002 Ano,510015 Ano,510021 Ano,510023 Ano,510045 Ano,510057 Ano,510088 Ano,510101 Ano,510135 Ano,62688 Ano,63034 Ano,64105 Ano,689 Ano,759 Ano,778 Ano,900221 Ano,931 Ano,AG.240042 Ano,AG.240043 Ano,AG.240130 Ano,Ação de Governo,Ano,Anulado,Atualizado em,Categoria,Categoria Econômica,Contrato,Convênio,Data de Homologação,Desdobramento da Despesa,Detalhamento da Fonte,Em Liquidação,Empenhado,Esfera,Fonte de Recursos,Função,Grupo da Despesa,IE,Licitação,Liquidado,Modalidade de Aplicação,Natureza da Despesa,No Contrato,Nota Explicativa,Nr. Licitação,Número da Licitação,Órgão,Pago,Período,Processo Administrativo,Processo da Compra,Programa de Governo,SubFunção,Tipo Empenho,Unidade,Unidade Gestora_y
1322,SINGULAR GESTAO DE SERVICOS LTDA,11/01/2016,5.0,PREFEITURA DE MACAÉ - 0000,"R$ 0,00","R$ 0,00","R$ 2.366.079,38","R$ 2.366.079,38","R$ 2.366.079,38","<table cellpadding=""1px"" cellspacing=""0px"" cla...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,294 - Alimentação Escolar,2015,"R$ 0,00",28/12/2019 00:31,Comum,3 - DESPESAS CORRENTES,NaN,NaN,NaN,3.3.90.39.41 - FORNECIMENTO DE ALIMENTACAO,0 -,"R$ 0,00","R$ 2.366.079,38",Fiscal,RECURSOS ORDINÁRIOS - TESOURO,12 - Educação,3.3 - OUTRAS DESPESAS CORRENTES,NaN,Pregão Presencial,"R$ 2.366.079,38",3.3.90 - Aplicações Diretas,3.3.90.39 - OUTROS SERVIÇOS DE TERCEIROS - PE...,NaN,NaN,NaN,003/15,SECRETARIA MUNICIPAL DE EDUCAÇÃO,"R$ 2.366.079,38",Janeiro a Dezembro,/0,Processo da Compra:,112 - UNIVERSALIZAÇÃO DO ATENDIMENTO AO ESCO...,361 - Ensino Fundamental,Orçamentário,Secretaria Municipal de Educação,PREFEITURA DE MACAÉ - 0000

In [6]:
for i in df:
    print(i)

Credor
Data Emissão Empenho
Número do Empenho
Unidade Gestora
Valor Anulado
Valor Em Liquidação
Valor Empenhado
Valor Liquidado
Valor Pago
detalhe_empenho
0    Ano
0034    Ano
0052    Ano
0176    Ano
0180    Ano
0182    Ano
072    Ano
1164    Ano
14165    Ano
14166    Ano
1701996    Ano
170996    Ano
171145    Ano
171447    Ano
171586    Ano
171810    Ano
172265    Ano
18051    Ano
200    Ano
22771    Ano
23010    Ano
23018    Ano
24969    Ano
26409    Ano
280010    Ano
280016    Ano
280017    Ano
280022    Ano
280023    Ano
280031    Ano
280036    Ano
280038    Ano
280040    Ano
280051    Ano
280072    Ano
280078    Ano
280125    Ano
28531    Ano
28532    Ano
28533    Ano
2981    Ano
30425    Ano
30426    Ano
34    Ano
421    Ano
426    Ano
510001    Ano
510002    Ano
510015    Ano
510021    Ano
510023    Ano
510045    Ano
510057    Ano
510088    Ano
510101    Ano
510135    Ano
62688    Ano
63034    Ano
64105    Ano
689    Ano
759    Ano
778    Ano
900221    Ano
931    Ano
AG.240042    Ano
AG.240043    Ano
AG.240130    Ano
Ação de Governo
Ano
Anulado
Atualizado em
Categoria
Categoria Econômica
Contrato
Convênio
Credor.1
Data de Homologação
Desdobramento da Despesa
Detalhamento da Fonte
Em Liquidação
Empenhado
Esfera
Fonte de Recursos
Função
Grupo da Despesa
IE
Licitação
Liquidado
Modalidade de Aplicação
Natureza da Despesa
No Contrato
Nota Explicativa
Nr. Licitação
Número Empenho
Número da Licitação
Órgão
Pago
Período
Processo Administrativo
Processo da Compra
Programa de Governo
SubFunção
Tipo Empenho
Unidade
Unidade Gestora.1